export const ROOT_PATH = "/";
export const PROJECTS_PAGE = "projectsPage";
export const TASK_PAGE = "taskPage";
export const EMPLOYEES_PAGE = "employeesPage";
export const PROJECT_FORM = "projectForm";
export const TASK_FORM = "taskForm";
export const EMPLOYEE_FORM = "employeeForm";
export const buildUpdateProjectPath = (id: string) => `projectForm/${id}`;
export const buildUpdateTaskPath = (id: string) => `taskForm/${id}`;
export const buildUpdateEmployeePath = (id: string) => `employeeForm/${id}`;
